algoritmo "Contagem"
// Função :
// Autor :
// Data : 7/4/2018
// Seção de Declarações 
var
n1,n2,cont:real
inicio
Escreva("Digite o numero inicial: ")
Leia(N1)
Escreva("Digite o numero final: ")
Leia(n2)
Se (n1<n2) entao
   Escreval(n1)
   Enquanto (n1<n2) Faca
   n1 <- n1+1
   Escreval(n1)
   Fimenquanto
Senao
   Escreval(n1)
   Enquanto (n1>n2) Faca
   n1 <- n1-1
   Escreval(n1)
   Fimenquanto

Fimse
Fimalgoritmo
