algoritmo "semnome"
// Função :
// Autor :
// Data : 6/4/2018
// Seção de Declarações
var
i,f:real
inicio
escreva("digite o numero inicial: ")
leia(i)
escreva(" digite o numero final: ")
leia(f)
se (i>f)entao
   enquanto (i>= f) Faca
      i <- i - 1
      escreval(i)
   fimenquanto
senao
   se (i< f) entao
      enquanto (i<= f) Faca
         i <- i +1
         escreval(i)
      fimenquanto
   fimse

fimse
fimalgoritmo
